# Generated by Django 2.2.7 on 2020-05-25 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maincat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='prod_img')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maincat.Catagory')),
            ],
        ),
    ]
