# Generated by Django 2.2.7 on 2020-05-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincat', '0002_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='publish',
            field=models.BooleanField(default=1),
        ),
    ]
